Repository stolostron/acm-aap-aas-operations, pull requests merged in 2022-05, with the labels that each got.

#86 to add cloud credentials since storage secret is git ignored
  ansible-playbooks/roles/enable-oadp-object-storage/tasks/main.yml
  ansible-playbooks/roles/enable-oadp-object-storage/templates/cloud-credentials-azure
Labels: lgtm, approved

#87 Add an overlay to disable alert forwarding policy for DEV testing
  Makefile
  cluster-bootstrap/README.md
  cluster-bootstrap/alert-manager-config/overlay/dev-noalerts/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/dev-noalerts/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/alert-manager-config/noalerts/application.yaml
  cluster-bootstrap/argocd-apps/dev/alert-manager-config/noalerts/kustomization.yaml
  scripts/install-alertmanager.sh
Labels: lgtm, approved

#88 PR Test GH Action Pipeline
  .github/workflows/pr-check.yml
  scripts/ci-deploy-resources/pipeline.yaml
  scripts/ci-deploy-resources/pipelinerun.yaml
  scripts/ci-deploy-resources/sample-pvc.yaml
  scripts/ci-deploy-resources/secrets.yaml
  scripts/ci-deploy-resources/tasks.yaml
  scripts/ci-deploy.sh
Labels: lgtm, approved

#90 Update README.md
  ansible-playbooks/README.md
Labels: lgtm, approved

#91 Update README.md
  ansible-playbooks/README.md
Labels: lgtm, approved

#95 Fix README merge
  ansible-playbooks/README.md
Labels: lgtm, approved

#97 Add manifest check
  .github/workflows/manifest-check.yaml
  scripts/validate_manifests.sh
Labels: lgtm, approved

#98 Add Argocd vault plugin docker file
  cluster-bootstrap/openshift-gitops/config/Dockerfile
Labels: lgtm, approved

#100 to add sminonne key
  ansible-playbooks/roles/authorized-key/vars/main.yml
Labels: lgtm, approved

#96 add the alertmanager-to-github to auto-create issue for alert
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/alertmanager-to-github/base/alert-blocklist.yaml
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/alertmanager-to-github/base/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/base/secret.yaml
  cluster-bootstrap/alertmanager-to-github/base/service.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/set-args.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/set-args.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/kustomization.yaml
Labels: lgtm, approved

#102 add alertmanager-to-github tool
  cluster-bootstrap/alert-manager-config/overlay/dev-noalerts/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml
  cluster-bootstrap/alertmanager-to-github/base/secret.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/patch-secret-anno-for-vault.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/patch-secret-anno-for-vault.yaml
  cluster-bootstrap/argocd-apps/base/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/base/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/patch-path.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/patch-path.yaml
Labels: lgtm, approved

#103 add proxy for webhook
  cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml
Labels: lgtm, approved

#104 add proxy
  cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml
Labels: lgtm, approved

#105 Add authorized-key
  ansible-playbooks/roles/authorized-key/vars/main.yml
Labels: approved

#106 add soli key
  ansible-playbooks/roles/authorized-key/vars/main.yml
Labels: approved

#107 To fix restore issues (partial commit and other problems)
  ansible-playbooks/Makefile
  ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/create.yml
  ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/delete.yml
  ansible-playbooks/roles/restore-hub/tasks/main.yml
  ansible-playbooks/roles/restore-hub/templates/managedcluster.yml
  ansible-playbooks/roles/restore-hub/templates/restore-hub.yml
Labels: lgtm, approved

#109 Revert "Add configuration to encrypt etcd on the OpenShift cluster (#…
  cluster-bootstrap/argocd-apps/dev/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/dev/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/dev/patch-operator/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/patch-operator/kustomization.yaml
  cluster-bootstrap/openshift-config/README.md
  cluster-bootstrap/openshift-config/base/apiserver-patch.yaml
  cluster-bootstrap/openshift-config/base/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
  cluster-bootstrap/patch-operator/base/kustomization.yaml
  cluster-bootstrap/patch-operator/base/namespace.yaml
  cluster-bootstrap/patch-operator/base/operatorgroup.yaml
  cluster-bootstrap/patch-operator/base/subscription.yaml
  cluster-bootstrap/patch-operator/overlay/dev/kustomization.yaml
  scripts/install.sh
Labels: lgtm, approved

#111 update the alertmanager-to-github
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/alertmanager-to-github/base/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/base/route.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/dev/set-args.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/set-args.yaml
Labels: lgtm, approved

#112 Enable PG for dev env
  cluster-bootstrap/alert-manager-config/overlay/dev/app-alertmanager-config.yaml
Labels: lgtm, approved

#110 Add configuration to encrypt etcd on the OpenShift cluster
  cluster-bootstrap/argocd-apps/dev/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/dev/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/dev/patch-operator/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/patch-operator/kustomization.yaml
  cluster-bootstrap/openshift-config/README.md
  cluster-bootstrap/openshift-config/base/apiserver-patch.yaml
  cluster-bootstrap/openshift-config/base/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
  cluster-bootstrap/patch-operator/base/kustomization.yaml
  cluster-bootstrap/patch-operator/base/namespace.yaml
  cluster-bootstrap/patch-operator/base/operatorgroup.yaml
  cluster-bootstrap/patch-operator/base/subscription.yaml
  cluster-bootstrap/patch-operator/overlay/dev/kustomization.yaml
  scripts/install.sh
Labels: lgtm, approved

#114 Update auto-create issue tool
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/alertmanager-to-github/base/body.tmpl
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/alertmanager-to-github/base/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/base/namespace.yaml
  cluster-bootstrap/alertmanager-to-github/base/owner-conf.yaml
  cluster-bootstrap/alertmanager-to-github/base/route.yaml
  cluster-bootstrap/alertmanager-to-github/base/title.tmpl
  cluster-bootstrap/alertmanager-to-github/overlay/stage/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/stage/patch-secret-anno-for-vault.yaml
Labels: lgtm, approved

#115 Create local overlay & scripts for quickly setup personal testing env
  Makefile
  cluster-bootstrap/README.md
  cluster-bootstrap/acm/overlay/local/kustomization.yaml
  cluster-bootstrap/acm/overlay/local/subscription.yaml
  cluster-bootstrap/alert-manager-config/overlay/local/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/local/kustomization.yaml
  cluster-bootstrap/argocd-apps/local/acm/application.yaml
  cluster-bootstrap/argocd-apps/local/acm/kustomization.yaml
  cluster-bootstrap/argocd-apps/local/grafana-dev/application.yaml
  cluster-bootstrap/argocd-apps/local/grafana-dev/kustomization.yaml
  cluster-bootstrap/argocd-apps/local/multicluster-observability/application.yaml
  cluster-bootstrap/argocd-apps/local/multicluster-observability/kustomization.yaml
  cluster-bootstrap/argocd-apps/local/prometheus-config/application.yaml
  cluster-bootstrap/argocd-apps/local/prometheus-config/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/local/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/local/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/local/resource-patch.yaml
  cluster-bootstrap/multicluster-observability/overlay/local/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/local/thanos-storage-aws-secret.yaml
  cluster-bootstrap/prometheus-config/overlay/local/kustomization.yaml
  scripts/install-alertmanager.sh
  scripts/install.sh
  scripts/local-install.env
Labels: lgtm, approved

#116 Remove stage overlay
  Makefile
  cluster-bootstrap/README.md
  cluster-bootstrap/acm-aap/overlay/stage/kustomization.yaml
  cluster-bootstrap/acm-channel/overlay/stage/kustomization.yaml
  cluster-bootstrap/acm/overlay/stage/kustomization.yaml
  cluster-bootstrap/acm/overlay/stage/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/stage/subscription.yaml
  cluster-bootstrap/alert-manager-config/overlay/stage/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/stage/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/acm-aap-application/application.yaml
  cluster-bootstrap/argocd-apps/stage/acm-aap-application/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/acm-channel/application.yaml
  cluster-bootstrap/argocd-apps/stage/acm-channel/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/acm/application.yaml
  cluster-bootstrap/argocd-apps/stage/acm/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/alert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/stage/alert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/alertmanager-to-github/patch-path.yaml
  cluster-bootstrap/argocd-apps/stage/cert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/stage/cert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/cert-manager/application.yaml
  cluster-bootstrap/argocd-apps/stage/cert-manager/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/cluster-logging/application.yaml
  cluster-bootstrap/argocd-apps/stage/cluster-logging/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/grafana-dev/application.yaml
  cluster-bootstrap/argocd-apps/stage/grafana-dev/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/multicluster-observability/application.yaml
  cluster-bootstrap/argocd-apps/stage/multicluster-observability/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/prometheus-config/application.yaml
  cluster-bootstrap/argocd-apps/stage/prometheus-config/kustomization.yaml
  cluster-bootstrap/cert-manager-config/overlay/dev-azure-issuer/api.certificate.yaml
  cluster-bootstrap/cert-manager-config/overlay/dev-azure-issuer/apps.certificate.yaml
  cluster-bootstrap/cert-manager-config/overlay/dev-azure-issuer/azure.public.clusterissuer.yaml
  cluster-bootstrap/cert-manager-config/overlay/dev-azure-issuer/azure.secret.yaml
  cluster-bootstrap/cert-manager-config/overlay/dev-azure-issuer/kustomization.yaml
  cluster-bootstrap/cert-manager/overlay/stage/kustomization.yaml
  cluster-bootstrap/cluster-logging/overlay/stage/kustomization.yaml
  cluster-bootstrap/cluster-logging/overlay/stage/subscription.yaml
  cluster-bootstrap/grafana-dev/overlay/stage/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/stage/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/stage/resource-patch.yaml
  cluster-bootstrap/multicluster-observability/overlay/stage/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/stage/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/multicluster-observability/overlay/stage/thanos-storage-aws-secret.yaml
  cluster-bootstrap/prometheus-config/overlay/stage/kustomization.yaml
Labels: approved

#122 update the cronjob version to v1
  OWNERS
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
Labels: lgtm, approved

#125 Remove tag from argovault image
  cluster-bootstrap/openshift-gitops/config/argocd.yaml
Labels: lgtm, approved

#126 Remove legacy stage manifest
  cluster-bootstrap/argocd-apps/stage/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/stage/patch-operator/kustomization.yaml
Labels: lgtm, approved

#129 SSO
  cluster-bootstrap/README.md
  cluster-bootstrap/argocd-apps/dev/sso/application.yaml
  cluster-bootstrap/argocd-apps/dev/sso/kustomization.yaml
  cluster-bootstrap/sso/README.md
  cluster-bootstrap/sso/base/aap-aas-admin-cluster-admin.rolebinding.yaml
  cluster-bootstrap/sso/base/acm-sre-group.yaml
  cluster-bootstrap/sso/base/github-client-secret.yaml
  cluster-bootstrap/sso/base/github-idp.yaml
  cluster-bootstrap/sso/base/kustomization.yaml
  cluster-bootstrap/sso/overlay/dev/kustomization.yaml
  scripts/install.sh
Labels: lgtm, approved

#127 Fix image CVE issue
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/openshift-gitops/config/Dockerfile
  cluster-bootstrap/openshift-gitops/config/README.md
  cluster-bootstrap/openshift-gitops/config/argocd.yaml
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
  cluster-bootstrap/prometheus-config/image/Dockerfile
  cluster-bootstrap/prometheus-config/image/README.md
  scripts/ci-deploy-resources/tasks.yaml
  tools/aap-metric-checker/Dockerfile
  tools/aap-metric-checker/README.md
  tools/aap-metric-checker/aap-metric-checker-policy.yaml
  tools/aap-metric-checker/aap-metric-checker.sh
  tools/check-aap-metrics/Dockerfile
  tools/tool-cli-image/Dockerfile
  tools/tool-cli-image/README.md
Labels: lgtm, approved

#130 update the image tag
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
  tools/aap-metric-checker/aap-metric-checker-policy.yaml
Labels: lgtm, approved

#132 revert dockerfile
  cluster-bootstrap/openshift-gitops/config/Dockerfile
Labels: lgtm, approved

#133 Config group sync operator
  cluster-bootstrap/group-sync/overlay/dev/github-access-token.yaml
  cluster-bootstrap/group-sync/overlay/dev/github-group-sync.yaml
  cluster-bootstrap/group-sync/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#135 Add local overlay for patch-operator and openshift-config
  cluster-bootstrap/openshift-config/overlay/local/kustomization.yaml
  cluster-bootstrap/patch-operator/overlay/local/kustomization.yaml
Labels: lgtm, approved

#136 Update requirements.yml
  collections/requirements.yml
Labels: lgtm, approved

#137 add new alert to monitor the managedcluster
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
  cluster-bootstrap/multicluster-observability/base/custom-metrics/custom-metrics.yaml
Labels: lgtm, approved

#134 Update SSO
  cluster-bootstrap/README.md
  cluster-bootstrap/sso/base/acm-sre-group.yaml
  cluster-bootstrap/sso/base/kustomization.yaml
  cluster-bootstrap/sso/overlay/dev/github-client-secret.yaml
  cluster-bootstrap/sso/overlay/dev/github-idp.yaml
  cluster-bootstrap/sso/overlay/dev/kustomization.yaml
  scripts/install.sh
Labels: lgtm, approved

#138 update alert interval
  cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
Labels: lgtm, approved

#139 Create Playbook to deploy ACM
  ansible-playbooks/playbooks/deploy.yml
  ansible-playbooks/roles/deploy/tasks/main.yml
  ansible-playbooks/roles/deploy/vars/main.yml
Labels: lgtm, approved

#143 add new alert for aap metric endpoint
  cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
Labels: lgtm, approved

#141 Refactor playbook
  ansible-playbooks/README.md
  ansible-playbooks/playbooks/deploy-acm-stack.yml
  ansible-playbooks/roles/deploy-acm-stack/tasks/main.yml
  ansible-playbooks/roles/deploy-acm-stack/vars/main.yml
Labels: lgtm, approved

#142 Add prod overlay
  cluster-bootstrap/acm/overlay/prod/kustomization.yaml
  cluster-bootstrap/acm/overlay/prod/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/prod/subscription.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/prod/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/prod/patch-secret-anno-for-vault.yaml
  cluster-bootstrap/argocd-apps/prod/acm/application.yaml
  cluster-bootstrap/argocd-apps/prod/acm/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/alert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/prod/alert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/patch-path.yaml
  cluster-bootstrap/argocd-apps/prod/grafana-dev/application.yaml
  cluster-bootstrap/argocd-apps/prod/grafana-dev/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/group-sync/application.yaml
  cluster-bootstrap/argocd-apps/prod/group-sync/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/multicluster-observability/application.yaml
  cluster-bootstrap/argocd-apps/prod/multicluster-observability/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/prod/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/prod/patch-operator/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/prometheus-config/application.yaml
  cluster-bootstrap/argocd-apps/prod/prometheus-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/sso/application.yaml
  cluster-bootstrap/argocd-apps/prod/sso/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/prod/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/prod/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/prod/resource-patch.yaml
  cluster-bootstrap/group-sync/overlay/prod/github-access-token.yaml
  cluster-bootstrap/group-sync/overlay/prod/github-group-sync.yaml
  cluster-bootstrap/group-sync/overlay/prod/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod/thanos-storage-aws-secret.yaml
  cluster-bootstrap/openshift-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/patch-operator/overlay/prod/kustomization.yaml
  cluster-bootstrap/prometheus-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/sso/overlay/prod/github-client-secret.yaml
  cluster-bootstrap/sso/overlay/prod/github-idp.yaml
  cluster-bootstrap/sso/overlay/prod/kustomization.yaml
  scripts/install.sh
Labels: lgtm, approved

#145 Add missing argocd app for local deployment
  cluster-bootstrap/argocd-apps/local/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/local/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/local/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/local/patch-operator/kustomization.yaml
Labels: lgtm, approved

#147 Change vars from dict to flat list as not supported by AWX injector
  ansible-playbooks/README.md
  ansible-playbooks/roles/bastion-setup/tasks/main.yml
  ansible-playbooks/roles/bastion-setup/vars/main.yml
Labels: lgtm, approved

#149 Update alertmanager-to-github argocd app
  ansible-playbooks/README.md
  cluster-bootstrap/argocd-apps/base/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/patch-path.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/patch-path.yaml
Labels: lgtm, approved

#150 update image tag to digest
  cluster-bootstrap/alertmanager-to-github/base/deployment.yaml
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
  scripts/ci-deploy-resources/tasks.yaml
  tools/aap-metric-checker/aap-metric-checker-policy.yaml
Labels: lgtm, approved

#151 Update acm stack deployment playbook
  ansible-playbooks/roles/deploy-acm-stack/tasks/main.yml
  ansible-playbooks/roles/deploy-acm-stack/templates/app-alertmanager-config.yaml.j2
  ansible-playbooks/roles/deploy-acm-stack/templates/argocd.yaml.j2
  ansible-playbooks/roles/deploy-acm-stack/templates/multiclusterhub-operator-pull-secret.yaml.j2
  ansible-playbooks/roles/deploy-acm-stack/templates/thanos-storage-aws-secret.yaml.j2
  cluster-bootstrap/argocd-apps/dev/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/prod/alertmanager-to-github/application.yaml
  scripts/uninstall.sh
Labels: lgtm, approved

#140 Add dockerfile
  tools/ansible-execution-environments/README.md
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/context/Dockerfile
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/context/_build/requirements.txt
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/context/_build/requirements.yml
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/execution-environment.yml
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/requirements.txt
  tools/ansible-execution-environments/azure_ee_supported_1.11.0/requirements.yml
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/context/Dockerfile
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/context/_build/requirements.txt
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/context/_build/requirements.yml
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/execution-environment.yml
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/requirements.txt
  tools/ansible-execution-environments/azure_ee_supported_1.12.0/requirements.yml
Labels: approved, do-not-merge/hold

#153 Let argocd manage itself
  cluster-bootstrap/argocd-apps/dev/argocd/application.yaml
  cluster-bootstrap/argocd-apps/dev/argocd/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod/argocd/application.yaml
  cluster-bootstrap/argocd-apps/prod/argocd/kustomization.yaml
  cluster-bootstrap/openshift-gitops/base/kustomization.yaml
  cluster-bootstrap/openshift-gitops/base/operatorgroup.yaml
  cluster-bootstrap/openshift-gitops/deploy/subscription.yaml
  cluster-bootstrap/openshift-gitops/overlay/dev/argocd.yaml
  cluster-bootstrap/openshift-gitops/overlay/dev/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/prod/argocd.yaml
  cluster-bootstrap/openshift-gitops/overlay/prod/kustomization.yaml
Labels: lgtm, approved
