Repository stolostron/acm-aap-aas-operations, pull requests merged in 2022-06, with the labels that each got.

#152 Disable group and update policy alerts
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/alertmanager-to-github/base/body.tmpl
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
Labels: lgtm, approved

#156 Create testing overlay & remove invalid overlays
  cluster-bootstrap/acm/overlay/testing/kustomization.yaml
  cluster-bootstrap/acm/overlay/testing/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/testing/subscription.yaml
  cluster-bootstrap/alert-manager-config/overlay/dev-noalerts/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/dev-private/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/testing/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/testing/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/testing/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/testing/patch-secret-anno-for-vault.yaml
  cluster-bootstrap/argocd-apps/testing/acm/application.yaml
  cluster-bootstrap/argocd-apps/testing/acm/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/alert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/testing/alert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/testing/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/argocd/application.yaml
  cluster-bootstrap/argocd-apps/testing/argocd/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/grafana-dev/application.yaml
  cluster-bootstrap/argocd-apps/testing/grafana-dev/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/group-sync/application.yaml
  cluster-bootstrap/argocd-apps/testing/group-sync/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/multicluster-observability/application.yaml
  cluster-bootstrap/argocd-apps/testing/multicluster-observability/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/testing/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/testing/patch-operator/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/prometheus-config/application.yaml
  cluster-bootstrap/argocd-apps/testing/prometheus-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/testing/sso/application.yaml
  cluster-bootstrap/argocd-apps/testing/sso/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/testing/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/testing/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/testing/resource-patch.yaml
  cluster-bootstrap/group-sync/overlay/testing/github-access-token.yaml
  cluster-bootstrap/group-sync/overlay/testing/github-group-sync.yaml
  cluster-bootstrap/group-sync/overlay/testing/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/testing/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/testing/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/multicluster-observability/overlay/testing/thanos-storage-aws-secret.yaml
  cluster-bootstrap/openshift-config/overlay/testing/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/testing/argocd.yaml
  cluster-bootstrap/openshift-gitops/overlay/testing/kustomization.yaml
  cluster-bootstrap/patch-operator/overlay/testing/kustomization.yaml
  cluster-bootstrap/prometheus-config/overlay/testing/kustomization.yaml
  cluster-bootstrap/sso/overlay/testing/github-client-secret.yaml
  cluster-bootstrap/sso/overlay/testing/github-idp.yaml
  cluster-bootstrap/sso/overlay/testing/kustomization.yaml
Labels: lgtm, approved

#157 add new receiver and update the receiver conf
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
Labels: lgtm, approved

#154 verify acm-stack
  .gitignore
  ansible-playbooks/playbooks/deploy-acm-stack.yml
  ansible-playbooks/roles/deploy-acm-stack/tasks/main.yml
  ansible-playbooks/roles/deploy-acm-stack/vars/main.yml
Labels: lgtm, approved

#158 Temp fix auto issue generator env label issue
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/alert-manager-config/overlay/dev/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/testing/app-alertmanager-config.yaml
Labels: lgtm, approved

#148 Add playbook to setup an AAP controller workflow for Hub deployment
  ansible-playbooks/README.md
  ansible-playbooks/playbooks/aap-controller-workflow-dev.yml
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
  ansible-playbooks/playbooks/bastion.yml
  ansible-playbooks/playbooks/create-resource-group.yml
  ansible-playbooks/playbooks/update-inventory.yml
  ansible-playbooks/playbooks/vars/vars-adecorte.yml
  ansible-playbooks/playbooks/vars/vars-openshiftdev.yml
  ansible-playbooks/playbooks/vars/vars-rhaapdev.yml
  ansible-playbooks/playbooks/vars/vars-rhaapprod.yml
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
Labels: lgtm, approved

#161 update prod settings
  ansible-playbooks/playbooks/vars/vars-rhaapprod.yml
Labels: lgtm, approved

#162 Bump secret version to include new added mock aoc hook
  cluster-bootstrap/alert-manager-config/overlay/prod/app-alertmanager-config.yaml
Labels: lgtm, approved

#164 Bump version to update testing env slack hook url
  cluster-bootstrap/alert-manager-config/overlay/testing/app-alertmanager-config.yaml
Labels: lgtm, approved

#163 update rhaap vars file
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
  ansible-playbooks/playbooks/add-private-link-acm.yml
  ansible-playbooks/playbooks/vars/vars-rhaap.yml
Labels: lgtm, approved

#165 Improve kubeconfig upload to take into account changes
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
Labels: lgtm, approved

#167 Uniformize variables + minor fixes
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
  ansible-playbooks/playbooks/add-private-link-acm.yml
Labels: lgtm, approved

#169 Fix inventory name in workflow
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
Labels: lgtm, approved

#168 update import part 1
  ansible-playbooks/playbooks/import-aap-aks-collection.yml
  ansible-playbooks/roles/connect-aks-to-acm-hub-collection/tasks/create.yml
Labels: lgtm, approved

#171 Adding ssh key for jmighion.
  ansible-playbooks/roles/authorized-key/vars/main.yml
Labels: lgtm, approved

#170 Add dhageman's SSH key
  ansible-playbooks/roles/authorized-key/vars/main.yml
Labels: approved

#172 increase threshold for aap pod restart
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
Labels: approved

#175 add servicemonitor and update the doc
  tools/aap-metric-simulator/README.md
  tools/aap-metric-simulator/manifests/automation-controller-auth.yaml
  tools/aap-metric-simulator/manifests/deployment.yaml
  tools/aap-metric-simulator/manifests/kustomization.yaml
  tools/aap-metric-simulator/manifests/service.yaml
  tools/aap-metric-simulator/manifests/servicemonitor.yaml
Labels: lgtm, approved

#178 Disable github issue generator for testing env
  cluster-bootstrap/alert-manager-config/overlay/testing/app-alertmanager-config.yaml
Labels: lgtm, approved

#179 Disable AOC slack alert for dev env
  cluster-bootstrap/alert-manager-config/overlay/dev/app-alertmanager-config.yaml
Labels: lgtm, approved

#181 add secret for aap
  tools/aap-metric-simulator/README.md
  tools/aap-metric-simulator/manifests/automation-controller-admin-password.yaml
  tools/aap-metric-simulator/manifests/kustomization.yaml
Labels: lgtm, approved

#180 Disable ACM proxy addon for dev
  cluster-bootstrap/acm/overlay/dev/kustomization.yaml
  cluster-bootstrap/acm/overlay/dev/multiclusterhub.yaml
Labels: lgtm, approved

#177 Upgrade ACM to release 2.5 for dev env
  cluster-bootstrap/acm/overlay/dev/subscription.yaml
Labels: approved

#182 upgrade dev cluster acm1 to acm 2.5
  cluster-bootstrap/grafana-dev/overlay/dev/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/aap-alerts.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/kustomization.yaml
  cluster-bootstrap/prometheus-config/overlay/dev/aap-prom-conf-policy.yaml
  cluster-bootstrap/prometheus-config/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#183 Enable proxy addon
  cluster-bootstrap/acm/overlay/dev/kustomization.yaml
  cluster-bootstrap/acm/overlay/dev/multiclusterhub.yaml
Labels: lgtm, approved, do-not-merge/hold

#185 update the servicemonitor port
  cluster-bootstrap/prometheus-config/overlay/dev/aap-prom-conf-policy.yaml
  tools/aap-metric-simulator/manifests/service.yaml
  tools/aap-metric-simulator/manifests/servicemonitor.yaml
Labels: lgtm, approved

#186 upgrade the testing to 2.5
  cluster-bootstrap/acm/overlay/testing/subscription.yaml
Labels: lgtm, approved

#188 update the alertconf and alert
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/aap-alerts.yaml
Labels: lgtm, approved

#191 Disable acm proxy addon for prod
  cluster-bootstrap/acm/base/multiclusterhub.yaml
Labels: lgtm, approved

#193 Update monitoring config for acm 2.5 for prod
  cluster-bootstrap/grafana-dev/overlay/prod/kustomization.yaml
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/aap-alerts.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/kustomization.yaml
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
  cluster-bootstrap/prometheus-config/overlay/dev/aap-prom-conf-policy.yaml
  cluster-bootstrap/prometheus-config/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#194 Enable proxy addon for acm 2.5 for prod
  cluster-bootstrap/acm/base/multiclusterhub.yaml
  cluster-bootstrap/acm/overlay/dev/kustomization.yaml
  cluster-bootstrap/acm/overlay/dev/multiclusterhub.yaml
  cluster-bootstrap/acm/overlay/dev/patch-delete-old-cr-spec.yaml
Labels: lgtm, approved

#195 update label
  tools/aap-metric-simulator/manifests/deployment.yaml
  tools/aap-metric-simulator/manifests/service.yaml
  tools/aap-metric-simulator/manifests/servicemonitor.yaml
Labels: lgtm, approved

#189 Store SA in Azure Key Vault for import purposes
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
  ansible-playbooks/roles/bastion-ocp4-setup/templates/clusterrolebinding.yaml.j2
  ansible-playbooks/roles/bastion-ocp4-setup/templates/service-account-import.yaml.j2
Labels: lgtm, approved

#197 Remove overlay dev-managed-premium
  cluster-bootstrap/grafana-dev/overlay/dev-managed-premium/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/dev-managed-premium/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/dev-managed-premium/resource-patch.yaml
Labels: lgtm, approved

#173 Add playbook task for Argocd app
  ansible-playbooks/roles/deploy-acm-stack/tasks/main.yml
Labels: lgtm, approved

#198 Update local overlay
  cluster-bootstrap/acm/overlay/local/subscription.yaml
  cluster-bootstrap/grafana-dev/overlay/local/kustomization.yaml
Labels: lgtm, approved

#200 Add pull secret for mce
  cluster-bootstrap/acm/overlay/dev/multiclusterhub-operator-pull-secret copy.yaml
  cluster-bootstrap/acm/overlay/prod/multiclusterhub-operator-pull-secret copy.yaml
  cluster-bootstrap/acm/overlay/testing/multiclusterhub-operator-pull-secret copy.yaml
Labels: lgtm, approved

#199 Update SSO ClusterRoleBinding
  cluster-bootstrap/sso/base/aap-aas-admin-cluster-admin.rolebinding.yaml
Labels: lgtm, approved

#201 Fix ArgoCD RBAC with the correct group name, as the demo one does not exist
  ansible-playbooks/roles/deploy-acm-stack/templates/argocd.yaml.j2
  cluster-bootstrap/openshift-gitops/config/argocd.yaml
Labels: lgtm, approved

#203 Activate API certs on acm1
  cluster-bootstrap/openshift-config/overlay/dev/apiserver-certs-patch.yaml
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#202 Fixes for AAP redeployment
  ansible-playbooks/playbooks/aap-controller-workflow-setup.yml
  ansible-playbooks/playbooks/vars/vars-rhaapdev.yml
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
Labels: lgtm, approved

#204 Activate ingress certs in acm1
  cluster-bootstrap/openshift-config/overlay/dev/apps-ingresscontroller-patch.yaml
Labels: lgtm, approved

#205 Activate ingress certs in acm1
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#206 Fix error checking for kubeconfig and patch also user kubeconfig
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
Labels: lgtm, approved

#208 disable KubeStateMetricsListErrors
  cluster-bootstrap/alert-manager-config/base/alertmgr-policy-conf.yaml
Labels: lgtm, approved

#209 Rotate vault token for dev env
  cluster-bootstrap/openshift-gitops/overlay/dev/argocd.yaml
Labels: lgtm, approved

#190 Add policy to control OpenShift version upgrade on the Hub
  cluster-bootstrap/openshift-config/base/kustomization.yaml
  cluster-bootstrap/openshift-config/base/policy-openshift-cluster-version.yaml
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/local/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/testing/kustomization.yaml
Labels: lgtm, approved

#207 Add ACM policy to monitor certificate expiration on the Hub
  cluster-bootstrap/cert-manager-config/base/certificateexpirationpolicy.yaml
  cluster-bootstrap/cert-manager-config/base/kustomization.yaml
Labels: lgtm, approved

#210 Enable policy to trigger update to 4.10.16 in dev
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
Labels: lgtm, approved

#211 Disable pruning on openshift-config Argo app as it interferes with policies
  cluster-bootstrap/argocd-apps/dev/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/local/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/prod/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/testing/openshift-config/application.yaml
  cluster-bootstrap/openshift-config/base/policy-openshift-cluster-version.yaml
Labels: lgtm, approved

#213 Update install scripts to inlcude cert-manager argo app
  scripts/install.sh
Labels: lgtm, approved

#214 Don't patch apiserver/ingress controller to use certs on testing
  cluster-bootstrap/openshift-config/overlay/testing/apiserver-certs-patch.yaml
  cluster-bootstrap/openshift-config/overlay/testing/apps-ingresscontroller-patch.yaml
  cluster-bootstrap/openshift-config/overlay/testing/kustomization.yaml
Labels: lgtm, approved

#212 Add a policyset to group certificates related policies
  cluster-bootstrap/cert-manager-config/base/azure.public.clusterissuer.yaml
  cluster-bootstrap/cert-manager-config/base/certificateexpirationpolicy.yaml
  cluster-bootstrap/cert-manager-config/base/policyset-certificates.yaml
  cluster-bootstrap/cert-manager/base/csvpatch.yaml
Labels: lgtm, approved

#216 Forgot kustomization.yaml
  cluster-bootstrap/cert-manager-config/base/kustomization.yaml
Labels: lgtm, approved

#217 Align usage between playbooks for better clarity
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/defaults/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-adecorte.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-openshiftdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-rhaap-emea.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaap-emea.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapdev.yml
Labels: lgtm, approved

#218 Fix mce pull secret issue
  cluster-bootstrap/acm/base/kustomization.yaml
  cluster-bootstrap/acm/overlay/dev/kustomization.yaml
  cluster-bootstrap/acm/overlay/dev/mce-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/prod/kustomization.yaml
  cluster-bootstrap/acm/overlay/prod/mce-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/testing/kustomization.yaml
  cluster-bootstrap/acm/overlay/testing/mce-operator-pull-secret.yaml
Labels: lgtm, approved

#219 Add mce namespace
  cluster-bootstrap/acm/base/kustomization.yaml
  cluster-bootstrap/acm/base/mce-namespace.yaml
  cluster-bootstrap/acm/overlay/local/kustomization.yaml
Labels: lgtm, approved

#220 Remove namespace from kustomization.yaml
  cluster-bootstrap/openshift-config/base/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/dev/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/local/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/openshift-config/overlay/testing/kustomization.yaml
Labels: lgtm, approved

#221 update alerts interval and kustomization ns
  cluster-bootstrap/multicluster-observability/base/custom-alerts/README.md
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
  cluster-bootstrap/prometheus-config/base/aap-prom-conf-policy.yaml
  cluster-bootstrap/prometheus-config/base/kustomization.yaml
Labels: lgtm, approved

#222 Remove ns in kustomization.yaml to avoided the namespace overwrite issue
  cluster-bootstrap/alert-manager-config/base/kustomization.yaml
  cluster-bootstrap/alert-manager-config/overlay/dev/kustomization.yaml
  cluster-bootstrap/alert-manager-config/overlay/local/kustomization.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod/kustomization.yaml
  cluster-bootstrap/alert-manager-config/overlay/testing/kustomization.yaml
  cluster-bootstrap/cluster-logging/base/kustomization.yaml
  cluster-bootstrap/cluster-logging/overlay/dev/kustomization.yaml
  cluster-bootstrap/grafana-dev/base/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/dev/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/local/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/prod/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/testing/kustomization.yaml
  cluster-bootstrap/group-sync/base/kustomization.yaml
  cluster-bootstrap/multicluster-observability/base/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/dev/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/local/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/testing/kustomization.yaml
  cluster-bootstrap/openshift-gitops/base/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/dev/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/prod/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/testing/kustomization.yaml
Labels: lgtm, approved

#223 Bump ACM version for GitHub issues
  cluster-bootstrap/alertmanager-to-github/base/body.tmpl
Labels: lgtm, approved

#226 Remove duplicated subscription for gitops
  cluster-bootstrap/argocd-apps/dev/argocd/application.yaml
  cluster-bootstrap/argocd-apps/prod/argocd/application.yaml
  cluster-bootstrap/argocd-apps/testing/argocd/application.yaml
  cluster-bootstrap/openshift-gitops/deploy/subscription.yaml
Labels: lgtm, approved

#228 Update prod NA Pagerduty service key
  cluster-bootstrap/alert-manager-config/overlay/prod/app-alertmanager-config.yaml
Labels: lgtm, approved

#229 update alerts
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
Labels: lgtm, approved

#230 Update config based on latest changes
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-rhaapemea.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapemea.yml
Labels: lgtm, approved

#227 Create overlay for EMEA prod deployment
  cluster-bootstrap/acm/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/acm/overlay/prod-emea/mce-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/prod-emea/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/acm/overlay/prod-emea/subscription.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod-emea/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/alertmanager-to-github/overlay/prod-emea/patch-secret-anno-for-vault.yaml
  cluster-bootstrap/argocd-apps/prod-emea/acm/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/acm/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/alert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/alert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/alertmanager-to-github/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/alertmanager-to-github/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/argocd/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/argocd/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/cert-manager-config/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/cert-manager-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/cert-manager/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/cert-manager/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/grafana-dev/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/grafana-dev/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/group-sync/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/group-sync/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/multicluster-observability/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/multicluster-observability/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/openshift-config/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/openshift-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/patch-operator/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/patch-operator/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/prometheus-config/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/prometheus-config/kustomization.yaml
  cluster-bootstrap/argocd-apps/prod-emea/sso/application.yaml
  cluster-bootstrap/argocd-apps/prod-emea/sso/kustomization.yaml
  cluster-bootstrap/cert-manager-config/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/cert-manager/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/grafana-dev/overlay/prod-emea/pvc-patch.yaml
  cluster-bootstrap/grafana-dev/overlay/prod-emea/resource-patch.yaml
  cluster-bootstrap/group-sync/overlay/prod-emea/github-access-token.yaml
  cluster-bootstrap/group-sync/overlay/prod-emea/github-group-sync.yaml
  cluster-bootstrap/group-sync/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod-emea/multiclusterhub-operator-pull-secret.yaml
  cluster-bootstrap/multicluster-observability/overlay/prod-emea/thanos-storage-azure-secret.yaml
  cluster-bootstrap/openshift-config/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/openshift-gitops/overlay/prod-emea/argocd.yaml
  cluster-bootstrap/openshift-gitops/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/patch-operator/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/prometheus-config/overlay/prod-emea/kustomization.yaml
  cluster-bootstrap/sso/overlay/prod-emea/github-client-secret.yaml
  cluster-bootstrap/sso/overlay/prod-emea/github-idp.yaml
  cluster-bootstrap/sso/overlay/prod-emea/kustomization.yaml
Labels: lgtm, approved

#231 Expose a few more variables + add a label to templates
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/defaults/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/dev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-adecorte.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-openshiftdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapemea.yml
Labels: lgtm, approved

#232 Update bootstrap doc & refactor scripts
  Makefile
  cluster-bootstrap/README.md
Labels: lgtm, approved

#233 add cluster_url to alert
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts-policy.yaml
  cluster-bootstrap/multicluster-observability/base/custom-alerts/aap-alerts.yaml
  cluster-bootstrap/multicluster-observability/base/kustomization.yaml
Labels: lgtm, approved

#234 Add docs + some linting and clean up of the roles
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/README.md
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-secret-sync/vars/vars-rhaapdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/README.md
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/dev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/main.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-adecorte.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-openshiftdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaap.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapdev.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/vars/vars-rhaapemea.yml
Labels: lgtm, approved

#237 Add ansible task to auto approve acm install plan
  ansible-playbooks/roles/deploy-acm-stack/tasks/main.yml
  scripts/install.sh
Labels: lgtm, approved

#241 Check kubeconfig certificates before the upload
  ansible-playbooks/roles/bastion-ocp4-setup/tasks/main.yml
Labels: lgtm, approved

#238 Skip subnet patching if we have a NAT Gateway created with ocp4-ipi installer
  ansible-playbooks/playbooks/add-private-link-acm.yml
  ansible-playbooks/roles/aap-controller-acm-workflow-setup/tasks/main.yml
Labels: lgtm, approved

#242 Update prod slack token
  cluster-bootstrap/alert-manager-config/overlay/prod-emea/app-alertmanager-config.yaml
  cluster-bootstrap/alert-manager-config/overlay/prod/app-alertmanager-config.yaml
Labels: lgtm, approved

#245 AAP-4480: Activate some ansible-lint checks
  .ansible-lint
  ansible-playbooks/roles/bastion-setup/tasks/main.yml
  ansible-playbooks/roles/import-managedcluster-default-invoke/tasks/delete.yml
  ansible-playbooks/roles/k8s-operator-mgmt/tasks/ensure-operator-version.yml
  ansible-playbooks/roles/k8s-operator-mgmt/tasks/installplan-csv.yml
  ansible-playbooks/roles/setup-public-dns-zone/tasks/main.yml
Labels: lgtm, approved

#246 Update ci deploy to testing env
  .github/workflows/pr-check.yml
  scripts/ci-deploy-resources/pipeline.yaml
  scripts/ci-deploy-resources/pipelinerun.yaml
  scripts/ci-deploy-resources/tasks.yaml
  scripts/ci-deploy.sh
Labels: lgtm, approved
